version: "2"

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - broker-kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  broker-kafka:
    driver: bridge